"""Parity against a frozen oracle generated by installed NLTK 3.10.3."""

from __future__ import annotations

import hashlib
import itertools
import json
import random
from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol, cast

import pytest

from temnia_pipeline.evals.nltk_metrics import ghd, pk, windowdiff

if TYPE_CHECKING:
    from collections.abc import Callable

FIXTURE = Path(__file__).parent / "fixtures" / "nltk_metrics_oracle.json"
COSTS = ((2.0, 2.0, 1.0), (1.0, 1.0, 0.5), (1.0, 2.0, 0.5), (3.0, 0.25, 2.0))


class DigestWriter(Protocol):
    """The one hashlib operation used by the compact oracle."""

    def update(self, data: bytes, /) -> None:
        """Add bytes to the digest."""


def _oracle() -> dict[str, Any]:
    return cast("dict[str, Any]", json.loads(FIXTURE.read_text()))


def _bits(length: int) -> tuple[str, ...]:
    return tuple("".join(value) for value in itertools.product("01", repeat=length))


def _add(hasher: DigestWriter, *parts: object) -> None:
    hasher.update(("\t".join(str(part) for part in parts) + "\n").encode())


def test_exhaustive_pk_and_windowdiff_match_frozen_nltk_oracle() -> None:
    digest = hashlib.sha256()
    comparisons = 0
    for length in range(1, 6):
        values = _bits(length)
        for reference in values:
            for hypothesis in values:
                for window in range(1, length + 1):
                    _add(
                        digest,
                        "pk",
                        length,
                        reference,
                        hypothesis,
                        window,
                        pk(reference, hypothesis, window).hex(),
                    )
                    _add(
                        digest,
                        "windowdiff",
                        length,
                        reference,
                        hypothesis,
                        window,
                        windowdiff(reference, hypothesis, window).hex(),
                    )
                    comparisons += 2
    expected = _oracle()["groups"]["exhaustivePkWindowdiff"]
    assert comparisons == expected["comparisons"]
    assert digest.hexdigest() == expected["sha256"]


def test_exhaustive_ghd_matches_symmetric_and_asymmetric_nltk_oracle() -> None:
    digest = hashlib.sha256()
    comparisons = 0
    for length in range(1, 6):
        values = _bits(length)
        for reference in values:
            for hypothesis in values:
                for costs in COSTS:
                    _add(
                        digest,
                        "ghd",
                        length,
                        reference,
                        hypothesis,
                        *costs,
                        ghd(reference, hypothesis, *costs).hex(),
                    )
                    comparisons += 1
    expected = _oracle()["groups"]["exhaustiveGhd"]
    assert comparisons == expected["comparisons"]
    assert digest.hexdigest() == expected["sha256"]


def test_seeded_sparse_and_dense_long_cases_match_nltk_oracle() -> None:
    oracle = _oracle()
    generator = random.Random(oracle["seed"])  # noqa: S311 - frozen metric oracle
    digest = hashlib.sha256()
    comparisons = 0
    for case in oracle["longCases"]:
        length = int(case["length"])
        density = float(case["density"])
        reference = "".join("1" if generator.random() < density else "0" for _ in range(length))
        hypothesis = "".join("1" if generator.random() < density else "0" for _ in range(length))
        for window in (1, max(1, length // 7), length):
            _add(
                digest,
                "pk",
                length,
                density,
                reference,
                hypothesis,
                window,
                pk(reference, hypothesis, window).hex(),
            )
            _add(
                digest,
                "windowdiff",
                length,
                density,
                reference,
                hypothesis,
                window,
                windowdiff(reference, hypothesis, window).hex(),
            )
            comparisons += 2
        _add(
            digest,
            "ghd",
            length,
            density,
            reference,
            hypothesis,
            *COSTS[0],
            ghd(reference, hypothesis, *COSTS[0]).hex(),
        )
        comparisons += 1
    expected = oracle["groups"]["seededLong"]
    assert comparisons == expected["comparisons"]
    assert digest.hexdigest() == expected["sha256"]


@pytest.mark.parametrize("metric", [pk, windowdiff])
def test_window_metrics_reject_invalid_inputs(
    metric: Callable[[str, str, int], float],
) -> None:
    with pytest.raises(ValueError, match="unequal length"):
        metric("0", "00", 1)
    with pytest.raises(ValueError, match="only '0' and '1'"):
        metric("x", "0", 1)
    for window in (0, 2, True, 1.5):
        with pytest.raises(ValueError, match="window width"):
            metric("0", "0", cast("int", window))


@pytest.mark.parametrize("cost", [-1.0, float("nan"), float("inf"), True])
def test_ghd_rejects_nonfinite_or_negative_costs(cost: float) -> None:
    with pytest.raises(ValueError, match="finite nonnegative"):
        ghd("1", "0", insert_cost=cost)
