import { sql } from "drizzle-orm";
import { timestamp, uuid } from "drizzle-orm/pg-core";

/** UUIDv7 primary key generated by Postgres 18 (`uuidv7()` is built in). */
export const id = () => uuid("id").primaryKey().default(sql`uuidv7()`);

export const createdAt = () =>
  timestamp("created_at", { mode: "date", withTimezone: true })
    .notNull()
    .defaultNow();

export const updatedAt = () =>
  timestamp("updated_at", { mode: "date", withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());
