# Generated from packages/contracts/schemas/contracts.json by scripts/gen_contracts.py.
# Do not edit; change the Zod schema and regenerate (pnpm --filter @temnia/pipeline contracts).
# ruff: noqa
# generated by datamodel-codegen:
#   filename:  contracts.json

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel
from uuid import UUID


class Model(RootModel[Any]):
    root: Any


class HelloOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    greeting: str
    organizationId: Annotated[
        UUID, Field(description="Echoed from the input scope, never invented.")
    ]
    workerLanguage: Literal["python"]
    workerHost: str


class Scope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organizationId: Annotated[
        UUID, Field(description="The organization every row is scoped to.")
    ]
    userId: Annotated[
        UUID, Field(description="The acting user inside that organization.")
    ]


class HelloInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope: Scope
    name: Annotated[
        str, Field(description="Who to greet.", max_length=80, min_length=1)
    ]
