# Generated from packages/contracts/schemas/contracts.json by scripts/gen_contracts.py.
# Do not edit; change the Zod schema and regenerate (pnpm --filter @temnia/pipeline contracts).
# pyright: reportInvalidTypeForm=false
# ruff: noqa
# generated by datamodel-codegen:
#   filename:  contracts.json

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr
from enum import Enum, StrEnum
from uuid import UUID
from typing_extensions import TypeAliasType


class Model(RootModel[Any]):
    root: Any


class ArtifactKind(StrEnum):
    master = "master"
    hls = "hls"
    peaks = "peaks"
    thumbnails = "thumbnails"
    audio = "audio"
    shots = "shots"


class ArtifactRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contentType: Annotated[str, Field(min_length=1)]
    kind: ArtifactKind
    metadata: dict[str, Any]
    sizeBytes: Annotated[int, Field(ge=0, le=9007199254740991)]
    storageKey: Annotated[str, Field(min_length=1)]
    storagePrefix: str | None


class Status(StrEnum):
    pass_ = "pass"
    warn = "warn"
    fail = "fail"


class ChapterCheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected: float | None
    measured: float | None
    message: str
    name: Annotated[str, Field(min_length=1)]
    sectionId: Annotated[str, Field(max_length=256, min_length=1)]
    status: Status


class EditorialStatus(StrEnum):
    not_run = "not_run"
    passed = "passed"
    needs_review = "needs_review"
    failed = "failed"


class ChapterChecks(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    editorialReasons: list[str]
    editorialStatus: EditorialStatus
    editSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    technicalChecks: list[ChapterCheck]
    verifierFamily: str | None
    version: Literal[1]


class Kind(StrEnum):
    keep = "keep"
    drop = "drop"


class QuoteWordId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class ChapterProposalSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    firstSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    kind: Kind
    lastSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    quoteWordIds: list[QuoteWordId]
    reason: str
    title: str


class ChapterReviewAction(StrEnum):
    accept = "accept"
    reject = "reject"
    nudge = "nudge"
    restore = "restore"
    merge = "merge"
    undo = "undo"
    retry = "retry"
    cancel = "cancel"
    raise_budget = "raise_budget"


class State(StrEnum):
    applied = "applied"
    conflict = "conflict"
    refused = "refused"


class ChapterReviewOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: str
    mutationKey: UUID
    revision: Annotated[int | None, Field(ge=1, le=9007199254740991)]
    runId: UUID
    state: State


class Backend(StrEnum):
    recorded = "recorded"
    gateway = "gateway"


class ChapterRunConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    backend: Backend
    evidenceWindowSentences: Annotated[int, Field(ge=1, le=512)]
    maxDispatches: Annotated[int, Field(ge=1, le=128)]
    maxOutputTokens: Annotated[int, Field(ge=256, le=65536)]
    maxRenderConcurrency: Annotated[int, Field(ge=1, le=4)]
    maxRepairs: Annotated[int, Field(ge=0, le=3)]
    routeSnapshotId: Annotated[str, Field(max_length=256, min_length=1)]


class ReviewState(StrEnum):
    proposed = "proposed"
    accepted = "accepted"
    rejected = "rejected"


class ChapterSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endBoundaryId: Annotated[str, Field(max_length=256, min_length=1)]
    flags: list[str]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    kind: Kind
    quoteWordIds: list[QuoteWordId]
    reason: str
    reviewState: ReviewState
    startBoundaryId: Annotated[str, Field(max_length=256, min_length=1)]
    title: str


class HarnessArtifactKind(StrEnum):
    evidence = "evidence"
    proposal = "proposal"
    model_response = "model_response"
    edit = "edit"
    render = "render"
    checks = "checks"
    export = "export"
    speech_checkpoint = "speech_checkpoint"
    speech_assignment = "speech_assignment"


class HarnessArtifactRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fingerprint: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    id: UUID
    kind: HarnessArtifactKind
    sha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    sizeBytes: Annotated[int, Field(ge=0, le=9007199254740991)]
    storageKey: Annotated[str, Field(max_length=2048, min_length=1)]


class Kind2(StrEnum):
    edge = "edge"
    sentence = "sentence"
    turn = "turn"
    pause = "pause"
    shot = "shot"


class HarnessBoundaryCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    clearanceMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    kind: Kind2
    reasons: list[str]
    requiresReview: bool
    score: float
    sentenceId: Annotated[str | None, Field(max_length=256, min_length=1)]
    timeMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class Gateway(StrEnum):
    vercel = "vercel"
    openrouter = "openrouter"


class TopicShotDetector(StrEnum):
    pyscenedetect_adaptive = "pyscenedetect-adaptive"
    scdet = "scdet"


class HarnessConfigLimits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evidenceWindowSentences: Annotated[int, Field(ge=1, le=512)]
    maxDispatches: Annotated[int, Field(ge=1, le=128)]
    maxInFlightPerRoute: Annotated[int, Field(ge=1, le=8)]
    maxOutputTokens: Annotated[int, Field(ge=256, le=65536)]
    maxRenderConcurrency: Annotated[int, Field(ge=1, le=4)]
    maxRepairs: Annotated[int, Field(ge=0, le=3)]
    maxRunBudgetMicros: Annotated[int, Field(gt=0, le=9007199254740991)]
    minDispatchIntervalSeconds: Annotated[float, Field(ge=0.0, le=30.0)]


class Backend2(StrEnum):
    local = "local"
    modal = "modal"


class Encoder(StrEnum):
    libx264 = "libx264"
    h264_nvenc = "h264_nvenc"


class HarnessConfigRender(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    backend: Backend2
    encoder: Encoder


class HarnessConfigRouteSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(pattern="^[a-f0-9]{64}$")]
    path: Annotated[str, Field(min_length=1)]


class HarnessEvidencePause(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    leftWordId: Annotated[str | None, Field(max_length=256, min_length=1)]
    rightWordId: Annotated[str | None, Field(max_length=256, min_length=1)]
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class WordId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class HarnessEvidenceSentence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    speakers: list[str]
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    text: str
    wordIds: Annotated[list[WordId], Field(min_length=1)]


class HarnessEvidenceShot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    score: float
    timeMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class LineageId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class Timing(StrEnum):
    aligned = "aligned"
    interpolated = "interpolated"


class HarnessEvidenceWord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)]
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    lineageIds: list[LineageId]
    speaker: str | None
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    text: Annotated[str, Field(min_length=1)]
    timing: Timing
    wordIndex: Annotated[int, Field(ge=0, le=9007199254740991)]


class HarnessRunStatus(StrEnum):
    pending = "pending"
    running = "running"
    needs_review = "needs_review"
    ready = "ready"
    budget_paused = "budget_paused"
    outcome_unknown = "outcome_unknown"
    failed = "failed"
    cancelled = "cancelled"


class HelloOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    greeting: str
    organizationId: Annotated[
        UUID, Field(description="Echoed from the input scope, never invented.")
    ]
    workerHost: str
    workerLanguage: Literal["python"]


class IngestStage(StrEnum):
    probe = "probe"
    hls = "hls"
    publish = "publish"
    thumbnails = "thumbnails"
    audio = "audio"
    peaks = "peaks"
    shots = "shots"
    finalize = "finalize"


class PositiveRational(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    denominator: Annotated[int, Field(ge=1, le=9007199254740991)]
    numerator: Annotated[int, Field(ge=1, le=9007199254740991)]


class ProbeResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    audioChannels: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    audioCodec: str | None
    durationMs: Annotated[int, Field(gt=0, le=9007199254740991)]
    fps: Annotated[float | None, Field(gt=0.0)]
    height: Annotated[int | None, Field(gt=0, le=9007199254740991)]
    sizeBytes: Annotated[int, Field(ge=0, le=9007199254740991)]
    variableFrameRate: bool
    videoCodec: str | None
    width: Annotated[int | None, Field(gt=0, le=9007199254740991)]


class RationalTime(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    denominator: Annotated[int, Field(ge=1, le=9007199254740991)]
    numerator: Annotated[int, Field(ge=0, le=9007199254740991)]


class Scope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organizationId: Annotated[
        UUID, Field(description="The organization every row is scoped to.")
    ]
    userId: Annotated[
        UUID, Field(description="The acting user inside that organization.")
    ]


class SeededScope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organizationId: Literal["0192e8a0-0000-7000-8000-000000000001"]
    userId: Literal["0192e8a0-0000-7000-8000-000000000002"]


class SignedRationalTime(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    denominator: Annotated[int, Field(ge=1, le=9007199254740991)]
    numerator: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class Status1(StrEnum):
    unknown = "unknown"
    clear = "clear"
    needs_review = "needs_review"


class SpeechCoverageInterval(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class Status2(StrEnum):
    passed = "passed"
    needs_review = "needs_review"
    rejected = "rejected"


class GeneratorFamily(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class WorkItemId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class OpportunityId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class TopicAuthorWorkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    batchOrdinal: Annotated[int, Field(ge=0, le=9007199254740991)]
    opportunityIds: Annotated[list[OpportunityId], Field(max_length=12, min_length=1)]
    ordinal: Annotated[int, Field(ge=0, le=9007199254740991)]
    sectionId: Annotated[str, Field(max_length=256, min_length=1)]
    workItemId: Annotated[str, Field(max_length=256, min_length=1)]


class Edge(StrEnum):
    opening = "opening"
    ending = "ending"
    execution = "execution"


class SupportingSentenceId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class TopicBoundaryIssue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Literal["no-safe-cut"]
    edge: Edge
    reason: Annotated[str, Field(min_length=1)]
    supportingSentenceIds: Annotated[list[SupportingSentenceId], Field(min_length=1)]


class Classification(StrEnum):
    clean_handoff = "clean_handoff"
    misallocated_topic_extent = "misallocated_topic_extent"
    unresolved = "unresolved"


class Classification1(StrEnum):
    necessary_shared_context = "necessary_shared_context"
    misallocated_topic_extent = "misallocated_topic_extent"
    duplicate_core = "duplicate_core"
    unresolved = "unresolved"


class Relation(StrEnum):
    same_extent = "same_extent"
    inside_candidate = "inside_candidate"
    covers_candidate = "covers_candidate"
    opening_overlap = "opening_overlap"
    closing_overlap = "closing_overlap"


class TopicCandidateRegionHit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    firstSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    keywords: list[str]
    lastSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    parentId: Annotated[str, Field(max_length=256, min_length=1)]
    preview: str
    relation: Relation
    selectedFirstSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    selectedLastSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    sentenceCount: Annotated[int, Field(gt=0, le=9007199254740991)]
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class Status3(StrEnum):
    pass_ = "pass"
    fail = "fail"
    unknown = "unknown"


class Kind3(StrEnum):
    adjust_extent = "adjust_extent"
    retitle = "retitle"
    add = "add"
    drop = "drop"
    merge = "merge"
    split = "split"  # pyright: ignore[reportAssignmentType]


class TopicEditorialRubric(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assumedDomainKnowledge: list[str]
    audienceDescription: Annotated[str, Field(min_length=1)]
    exclusions: list[str]
    focus: str
    languagePolicy: Annotated[str, Field(min_length=1)]
    originalInstructions: str
    version: Literal[1]
    viewerGoals: list[str]


class BoundaryKind(Enum):
    edge = "edge"
    sentence = "sentence"
    turn = "turn"
    pause = "pause"
    shot = "shot"


class Kind4(StrEnum):
    sentence = "sentence"
    boundary = "boundary"
    pause = "pause"
    shot = "shot"
    speech_interval = "speech_interval"


class RelatedId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class TopicMediaEvidenceEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alignedWordCount: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    boundaryKind: BoundaryKind | None
    clearanceMs: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    endMs: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    interpolatedWordCount: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    kind: Kind4
    minimumConfidence: Annotated[float | None, Field(ge=0.0, le=1.0)]
    reasons: list[str]
    relatedIds: list[RelatedId]
    requiresReview: bool | None
    score: float | None
    sentenceId: Annotated[str | None, Field(max_length=256, min_length=1)]
    timeMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    wordCount: Annotated[int | None, Field(ge=0, le=9007199254740991)]


class SpeechCoverageStatus(StrEnum):
    unknown = "unknown"
    clear = "clear"
    needs_review = "needs_review"


class Disposition(StrEnum):
    proposed = "proposed"
    not_useful_for_audience = "not_useful_for_audience"
    not_contiguously_extractable = "not_contiguously_extractable"
    needs_evidence = "needs_evidence"


class SectionId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class Status4(StrEnum):
    represented = "represented"
    missing_candidate = "missing_candidate"
    duplicate_core = "duplicate_core"
    not_useful_for_audience = "not_useful_for_audience"
    not_contiguously_extractable = "not_contiguously_extractable"
    unresolved = "unresolved"


class TopicRenderedVideo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateId: Annotated[str, Field(max_length=256, min_length=1)]
    descriptor: HarnessArtifactRef
    execution: HarnessArtifactRef


class TopicRenders(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    editSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    format: Literal["topic-renders/1"]
    runId: UUID
    videos: list[TopicRenderedVideo]


class AuthorFamily(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class BrowseParentId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class CandidateId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class FindingId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class TopicRepairWorkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    browseParentIds: Annotated[list[BrowseParentId], Field(max_length=8, min_length=1)]
    candidateIds: Annotated[list[CandidateId], Field(max_length=8)]
    findingIds: Annotated[list[FindingId], Field(max_length=12, min_length=1)]
    opportunityIds: Annotated[list[OpportunityId], Field(max_length=24)]
    ordinal: Annotated[int, Field(ge=0, le=9007199254740991)]
    workItemId: Annotated[str, Field(max_length=256, min_length=1)]


class ExecutionStatus(StrEnum):
    complete = "complete"
    needs_review = "needs_review"
    execution_limited = "execution_limited"


class Disposition1(StrEnum):
    select = "select"
    decline = "decline"
    unresolved = "unresolved"


class Kind5(StrEnum):
    missing_setup = "missing_setup"
    missing_qualification = "missing_qualification"
    unfinished_discussion = "unfinished_discussion"
    unsupported_title = "unsupported_title"
    weak_viewer_value = "weak_viewer_value"
    unfocused_extent = "unfocused_extent"
    duplicate_core = "duplicate_core"
    missed_opportunity = "missed_opportunity"
    transcript_uncertainty = "transcript_uncertainty"
    physical_boundary_constraint = "physical_boundary_constraint"


class Severity(StrEnum):
    required = "required"
    preference = "preference"
    unknown = "unknown"


class Kind6(StrEnum):
    extend_start = "extend_start"
    extend_end = "extend_end"
    replace_extent = "replace_extent"
    replace_candidate = "replace_candidate"
    retitle = "retitle"
    merge = "merge"
    split = "split"  # pyright: ignore[reportAssignmentType]
    drop = "drop"
    add_opportunity = "add_opportunity"


class Origin(StrEnum):
    model = "model"
    human = "human"
    retained_diagnostic = "retained_diagnostic"


class TopicSentenceSpan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    firstSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    lastSentenceId: Annotated[str, Field(max_length=256, min_length=1)]


class ChildId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class Kind7(StrEnum):
    episode = "episode"
    section = "section"
    region = "region"


class TopicSourceIndexNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    childIds: list[ChildId]
    embedding: list[float]
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    firstSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    keywords: list[str]
    kind: Kind7
    lastSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    ordinal: Annotated[int, Field(ge=0, le=9007199254740991)]
    parentId: Annotated[str | None, Field(max_length=256, min_length=1)]
    preview: str
    sentenceCount: Annotated[int, Field(gt=0, le=9007199254740991)]
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class TopicSourceIndexSentence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    speakers: list[str]
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    text: str


class Kind8(StrEnum):
    section = "section"
    region = "region"


class TopicSourceNodeHit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    childCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    firstSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    keywords: list[str]
    kind: Kind8
    lastSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    parentId: Annotated[str, Field(max_length=256, min_length=1)]
    preview: str
    score: float | None
    sentenceCount: Annotated[int, Field(gt=0, le=9007199254740991)]
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class TopicSourceReadPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    complete: bool
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    nextSentenceId: Annotated[str | None, Field(max_length=256, min_length=1)]
    sentences: list[TopicSourceIndexSentence]


class TopicSourceReviewHandoffTask(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateIds: Annotated[list[CandidateId], Field(max_length=2, min_length=2)]
    leftContextSpan: TopicSentenceSpan
    rightContextSpan: TopicSentenceSpan


class ReviewerFamily(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class TopicSourceReviewOverlapTask(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateIds: Annotated[list[CandidateId], Field(max_length=2, min_length=2)]
    overlapSpan: TopicSentenceSpan


class ContextOpportunityId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class InspectionCandidateId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class Kind9(StrEnum):
    local = "local"
    omission = "omission"
    overlap = "overlap"
    handoff = "handoff"


class TopicSourceReviewWorkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    batchOrdinal: Annotated[int, Field(ge=0, le=9007199254740991)]
    candidateIds: Annotated[list[CandidateId], Field(max_length=4)]
    contextOpportunityIds: Annotated[list[ContextOpportunityId], Field(max_length=48)]
    discoverMissingOpportunities: bool
    handoffs: Annotated[list[TopicSourceReviewHandoffTask], Field(max_length=2)]
    inspectionCandidateIds: Annotated[list[InspectionCandidateId], Field(max_length=16)]
    kind: Kind9
    opportunityIds: Annotated[list[OpportunityId], Field(max_length=12)]
    ordinal: Annotated[int, Field(ge=0, le=9007199254740991)]
    overlaps: Annotated[list[TopicSourceReviewOverlapTask], Field(max_length=2)]
    sectionId: Annotated[str, Field(max_length=256, min_length=1)]
    sourceSpan: TopicSentenceSpan | None
    workItemId: Annotated[str, Field(max_length=256, min_length=1)]


class TopicSourceSearchPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    complete: bool
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    nextCursor: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    query: Annotated[str, Field(min_length=1)]
    regions: list[TopicSourceNodeHit]


class TranscribeInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifactPrefix: Annotated[
        str,
        Field(
            description="The source prefix; the transcript is written under it.",
            min_length=1,
        ),
    ]
    audioKey: Annotated[
        str,
        Field(
            description="The audio extract the provider reads; never the master.",
            min_length=1,
        ),
    ]
    durationMs: Annotated[
        int,
        Field(
            description="The probed duration; what the engine is metered against.",
            gt=0,
            le=9007199254740991,
        ),
    ]
    scope: Scope
    sourceId: UUID


class Action(StrEnum):
    replace = "replace"  # pyright: ignore[reportAssignmentType]
    delete = "delete"
    insert = "insert"
    split = "split"  # pyright: ignore[reportAssignmentType]
    merge = "merge"
    rename_speakers = "rename_speakers"
    reassign_speaker = "reassign_speaker"
    merge_speakers = "merge_speakers"
    undo = "undo"


class AffectedIdentityId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class Command(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["replace"]
    targetId: Annotated[str, Field(max_length=256, min_length=1)]
    text: Annotated[str, Field(max_length=200, min_length=1)]


class TargetId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class Command1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["delete"]
    targetIds: Annotated[list[TargetId], Field(max_length=200, min_length=1)]


class Side(StrEnum):
    before = "before"
    after = "after"


class Token(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class Command2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["insert"]
    anchorId: Annotated[str | None, Field(max_length=256, min_length=1)]
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    side: Side
    speakerIdentityId: Annotated[str | None, Field(max_length=256, min_length=1)]
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    tokens: Annotated[list[Token], Field(max_length=50, min_length=1)]


class Command3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["split"]
    targetId: Annotated[str, Field(max_length=256, min_length=1)]
    tokens: Annotated[list[Token], Field(max_length=50, min_length=1)]


class Command4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["merge"]
    targetIds: Annotated[list[TargetId], Field(max_length=200, min_length=1)]


LabelsAdditionalProperty = TypeAliasType(
    "LabelsAdditionalProperty", Annotated[str, Field(max_length=80, min_length=1)]
)


class Command5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["rename_speakers"]
    labels: dict[constr(min_length=1, max_length=256), LabelsAdditionalProperty]


class Command6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["reassign_speaker"]
    targetIds: Annotated[list[TargetId], Field(max_length=200, min_length=1)]
    targetSpeakerIdentityId: Annotated[str, Field(max_length=256, min_length=1)]


class SourceIdentityId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class Command7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["merge_speakers"]
    sourceIdentityIds: Annotated[
        list[SourceIdentityId], Field(max_length=200, min_length=1)
    ]
    targetIdentityId: Annotated[str, Field(max_length=256, min_length=1)]


class Command8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    mutationKey: UUID
    action: Literal["undo"]
    targetRevision: Annotated[int, Field(gt=0, le=9007199254740991)]


class DeletedIdentityId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class TranscriptProvider(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: Annotated[str, Field(min_length=1)]
    name: Annotated[str, Field(min_length=1)]
    version: Annotated[str, Field(min_length=1)]


class ParentIdentityId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class TranscriptSpeakerIdentity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identityId: Annotated[str, Field(max_length=256, min_length=1)]
    label: Annotated[str, Field(max_length=80)]
    parentIdentityIds: Annotated[list[ParentIdentityId], Field(max_length=500)]


class TranscriptStage(StrEnum):
    planning = "planning"
    download = "download"
    model = "model"
    transcribe = "transcribe"
    align = "align"
    diarize = "diarize"
    speech_coverage = "speech_coverage"
    write = "write"
    retrying = "retrying"


class TranscriptUtterance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    speaker: str | None
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class ParentId(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=1)]


class TimingOrigin(StrEnum):
    provider = "provider"
    manual = "manual"


class TranscriptWordIdentity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(max_length=256, min_length=1)]
    parentIds: Annotated[list[ParentId], Field(max_length=500)]
    timingOrigin: TimingOrigin


class WordTiming(StrEnum):
    aligned = "aligned"
    interpolated = "interpolated"


class ChapterBoundary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateId: Annotated[str | None, Field(max_length=256, min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    reasons: list[str]
    requiresReview: bool
    time: RationalTime
    timeMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class ChapterEditSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    boundaries: Annotated[list[ChapterBoundary], Field(min_length=2)]
    compilerVersion: Annotated[str, Field(min_length=1)]
    durationMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    evidenceArtifactId: UUID
    evidenceSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    sections: Annotated[list[ChapterSection], Field(min_length=1)]
    sourceAudioSampleRate: Annotated[int | None, Field(ge=1, le=9007199254740991)]
    sourceFrameRate: PositiveRational | None
    sourceId: UUID
    version: Literal[1]


class ChapterProposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sections: Annotated[list[ChapterProposalSection], Field(min_length=1)]
    summary: str
    version: Literal[1]


class ChapterRender(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    captions: HarnessArtifactRef | None
    checks: HarnessArtifactRef | None
    durationMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    editSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    media: HarnessArtifactRef
    sectionId: Annotated[str, Field(max_length=256, min_length=1)]


class ChapterRenders(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    editSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    format: Literal["chapter-renders/1"]
    renders: list[ChapterRender]
    runId: UUID


class ChapterReviewInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: ChapterReviewAction
    baseRevision: Annotated[int, Field(ge=0, le=9007199254740991)]
    boundaryId: Annotated[str | None, Field(max_length=256, min_length=1)]
    budgetMicros: Annotated[int | None, Field(ge=1, le=9007199254740991)]
    mutationKey: UUID
    otherSectionId: Annotated[str | None, Field(max_length=256, min_length=1)]
    reason: str
    runId: UUID
    scope: Scope
    sectionId: Annotated[str | None, Field(max_length=256, min_length=1)]
    sourceId: UUID
    targetRevision: Annotated[int | None, Field(ge=1, le=9007199254740991)]
    targetTimeMs: Annotated[int | None, Field(ge=0, le=9007199254740991)]


class ChapterRunInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    brief: Annotated[str | None, Field(max_length=100000)] = None
    budgetMicros: Annotated[int, Field(ge=1, le=9007199254740991)]
    config: ChapterRunConfig
    requestKey: UUID
    runId: UUID
    scope: Scope
    sourceId: UUID


class ChapterRunOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    editArtifact: HarnessArtifactRef | None
    errorMessage: str | None
    evidenceArtifact: HarnessArtifactRef | None
    revision: Annotated[int | None, Field(ge=1, le=9007199254740991)]
    runId: UUID
    status: HarnessRunStatus


class HarnessConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowRecorded: bool
    backend: Backend
    enabled: bool
    format: Literal["harness-config/1"]
    gateway: Gateway
    limits: HarnessConfigLimits
    recordedFixturePath: Annotated[str | None, Field(min_length=1)]
    render: HarnessConfigRender
    routeSnapshot: HarnessConfigRouteSnapshot
    topicShotDetector: TopicShotDetector


class HelloInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str, Field(description="Who to greet.", max_length=80, min_length=1)
    ]
    scope: Scope


class IngestInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifactPrefix: Annotated[
        str,
        Field(
            description="Prefix every derived artifact is written under; ends with '/'.",
            min_length=1,
        ),
    ]
    masterKey: Annotated[
        str, Field(description="The uploaded master's storage key.", min_length=1)
    ]
    scope: Scope
    sourceId: UUID


class IngestOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifacts: list[ArtifactRecord]
    organizationId: Annotated[
        UUID, Field(description="Echoed from the input scope, never invented.")
    ]
    probe: ProbeResult
    processingSeconds: Annotated[
        int,
        Field(
            description="Wall-clock seconds the worker spent.",
            ge=0,
            le=9007199254740991,
        ),
    ]
    sourceId: UUID
    storageBytes: Annotated[
        int,
        Field(
            description="Sum of the artifact rows written.", ge=0, le=9007199254740991
        ),
    ]


class SpeechCoverage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detector: str | None
    detectorHash: Annotated[str | None, Field(pattern="^[a-fA-F0-9]{64}$")]
    detectorRevision: str | None
    intervals: list[SpeechCoverageInterval]
    status: Status1
    uncoveredSpeechMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    uncoveredTailMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    warnings: list[str]


class TopicAuthorPackagingPlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["topic-author-packaging-plan/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inventorySha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    maxOpportunitiesPerWorkItem: Literal[12]
    workItems: list[TopicAuthorWorkItem]


class TopicCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    completionSpans: Annotated[list[TopicSentenceSpan], Field(min_length=1)]
    coreSpans: Annotated[list[TopicSentenceSpan], Field(min_length=1)]
    firstSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    lastSentenceId: Annotated[str, Field(max_length=256, min_length=1)]
    meaningChangingFollowups: list[TopicSentenceSpan]
    purpose: Annotated[str, Field(min_length=1)]
    reason: Annotated[str, Field(min_length=1)]
    requiredContextSpans: list[TopicSentenceSpan]
    title: Annotated[str, Field(min_length=1)]


class TopicCandidateHandoffJudgment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateIds: Annotated[list[str], Field(max_length=2, min_length=2)]
    classification: Classification
    leftContextSpan: TopicSentenceSpan
    reason: Annotated[str, Field(min_length=1)]
    recommendedLeftLastSentenceId: str | None
    recommendedRightFirstSentenceId: str | None
    rightContextSpan: TopicSentenceSpan


class TopicCandidateInspectionPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateId: Annotated[str, Field(max_length=256, min_length=1)]
    complete: bool
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    nextCursor: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    regions: list[TopicCandidateRegionHit]
    selectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]


class TopicCandidateOverlapJudgment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateIds: Annotated[list[str], Field(max_length=2, min_length=2)]
    classification: Classification1
    overlapSpan: TopicSentenceSpan
    reason: Annotated[str, Field(min_length=1)]


class TopicCompiledVideo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidate: TopicCandidate
    edit: ChapterEditSpec
    keptSectionId: Annotated[str, Field(max_length=256, min_length=1)]


class TopicCriterion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evidenceSpans: list[TopicSentenceSpan]
    reason: Annotated[str, Field(min_length=1)]
    status: Status3


class TopicEditSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compilerVersion: Annotated[str, Field(min_length=1)]
    durationMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    evidenceArtifactId: UUID
    evidenceSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    sourceId: UUID
    summary: Annotated[str, Field(min_length=1)]
    version: Literal[1]
    videos: list[TopicCompiledVideo]


class TopicEditorialPatchOperation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    affectedCandidateIds: list[str]
    kind: Kind3
    operationId: Annotated[str, Field(max_length=256, min_length=1)]
    replacementCandidates: list[TopicCandidate]


class TopicExport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    editSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    format: Literal["topic-export/1"]
    revision: Annotated[int, Field(gt=0, le=9007199254740991)]
    runId: UUID
    videos: list[TopicRenderedVideo]


class TopicInventorySection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nextSectionId: Annotated[str | None, Field(max_length=256, min_length=1)]
    ordinal: Annotated[int, Field(ge=0, le=9007199254740991)]
    ownershipSpan: TopicSentenceSpan
    previousSectionId: Annotated[str | None, Field(max_length=256, min_length=1)]
    sectionId: Annotated[str, Field(max_length=256, min_length=1)]


class TopicMediaEvidencePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    complete: bool
    detector: str | None
    detectorRevision: str | None
    events: list[TopicMediaEvidenceEvent]
    evidenceSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    nextCursor: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    sourceId: UUID
    span: TopicSentenceSpan
    speechCoverageStatus: SpeechCoverageStatus
    warnings: list[str]


class TopicOpportunity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateIds: list[str]
    completionSpans: list[TopicSentenceSpan]
    coreSpans: Annotated[list[TopicSentenceSpan], Field(min_length=1)]
    disposition: Disposition
    dispositionReason: Annotated[str, Field(min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    meaningChangingFollowups: list[TopicSentenceSpan]
    requiredContextSpans: list[TopicSentenceSpan]
    valueEvidenceSpans: Annotated[list[TopicSentenceSpan], Field(min_length=1)]
    viewerPurpose: Annotated[str, Field(min_length=1)]


class TopicOpportunityInventoryPlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["topic-opportunity-inventory-plan/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    sections: Annotated[list[TopicInventorySection], Field(min_length=1)]


class TopicOpportunityJudgment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateIds: list[str]
    evidenceSpans: Annotated[list[TopicSentenceSpan], Field(min_length=1)]
    opportunityId: Annotated[str, Field(max_length=256, min_length=1)]
    reason: Annotated[str, Field(min_length=1)]
    status: Status4


class TopicProposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidates: list[TopicCandidate]
    summary: Annotated[str, Field(min_length=1)]
    version: Literal[1]


class TopicRepairPlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assessmentSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    format: Literal["topic-repair-plan/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    maxCandidatesPerWorkItem: Literal[8]
    maxFindingsPerWorkItem: Literal[12]
    maxOpportunitiesPerWorkItem: Literal[24]
    selectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    workItems: Annotated[list[TopicRepairWorkItem], Field(min_length=1)]


class TopicSelectionDecision(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateId: Annotated[str, Field(max_length=256, min_length=1)]
    disposition: Disposition1
    evidenceSpans: Annotated[list[TopicSentenceSpan], Field(min_length=1)]
    reason: Annotated[str, Field(min_length=1)]


class TopicSelectionDraft(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    opportunities: list[TopicOpportunity]
    proposal: TopicProposal


class TopicSelectionFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    affectedCandidateIds: list[str]
    evidenceSpans: Annotated[list[TopicSentenceSpan], Field(min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    kind: Kind5
    opportunityIds: list[str]
    reason: Annotated[str, Field(min_length=1)]
    severity: Severity


class TopicSelectionPatchOperationV3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    affectedCandidateIds: list[str]
    findingIds: Annotated[list[str], Field(min_length=1)]
    id: Annotated[str, Field(max_length=256, min_length=1)]
    kind: Kind6
    opportunities: list[TopicOpportunity]
    reason: Annotated[str, Field(min_length=1)]
    replacementCandidates: list[TopicCandidate]


class TopicSelectionPatchV3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseSelectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    evidenceSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    operations: list[TopicSelectionPatchOperationV3]
    rubricSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    summary: Annotated[str, Field(min_length=1)]


class TopicSelectionRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    draft: TopicSelectionDraft
    evidenceSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    format: Literal["topic-selection/2"]
    origin: Origin
    parentSelectionSha256: Annotated[str | None, Field(pattern="^[a-fA-F0-9]{64}$")]
    rubric: TopicEditorialRubric
    rubricSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    runId: UUID


class TopicSourceBrowsePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    complete: bool
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    nextCursor: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    nodes: list[TopicSourceNodeHit]
    parentId: Annotated[str, Field(max_length=256, min_length=1)]


class TopicSourceIndex(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    embeddingDimensions: Annotated[int, Field(gt=0, le=9007199254740991)]
    embeddingModel: Annotated[str, Field(max_length=256, min_length=1)]
    embeddingRevision: Annotated[str, Field(max_length=256, min_length=1)]
    evidenceSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    format: Literal["topic-source-index/2"]
    nodes: Annotated[list[TopicSourceIndexNode], Field(min_length=3)]
    regionMaxCharacters: Annotated[int, Field(gt=0, le=9007199254740991)]
    regionMaxSentences: Annotated[int, Field(gt=0, le=9007199254740991)]
    rootNodeId: Annotated[str, Field(max_length=256, min_length=1)]
    sectionMaxRegions: Annotated[int, Field(gt=0, le=9007199254740991)]
    sentences: Annotated[list[TopicSourceIndexSentence], Field(min_length=1)]
    sourceId: UUID
    transcriptId: UUID
    transcriptRevision: Annotated[int, Field(gt=0, le=9007199254740991)]


class TopicSourceJudgment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateId: Annotated[str, Field(max_length=256, min_length=1)]
    completeContext: TopicCriterion
    distinctPurpose: TopicCriterion
    faithfulMeaning: TopicCriterion


class TopicSourceReview(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidates: list[TopicSourceJudgment]
    summary: Annotated[str, Field(min_length=1)]


class TopicSourceReviewPlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["topic-source-review-plan/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    maxCandidatesPerLocalWorkItem: Literal[4]
    maxOpportunitiesPerLocalWorkItem: Literal[12]
    maxPairsPerRelationshipWorkItem: Literal[2]
    selectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    workItems: Annotated[list[TopicSourceReviewWorkItem], Field(min_length=1)]


class TopicValueReview(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deliveredValue: TopicCriterion
    focusedDevelopment: TopicCriterion
    openingEffectiveness: TopicCriterion
    reconstructedPurpose: Annotated[str, Field(min_length=1)]
    reconstructedTakeaway: Annotated[str, Field(min_length=1)]
    viewerReasonToWatch: TopicCriterion


class TranscribeOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    durationMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    language: Annotated[str, Field(min_length=1)]
    organizationId: Annotated[
        UUID, Field(description="Echoed from the input scope, never invented.")
    ]
    provider: TranscriptProvider
    revision: Annotated[int, Field(gt=0, le=9007199254740991)]
    sourceId: UUID
    speakerCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    storageKey: Annotated[str, Field(min_length=1)]
    wordCount: Annotated[int, Field(ge=0, le=9007199254740991)]


class TranscriptRevisionAnnotations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    speakerIdentities: dict[
        constr(min_length=1, max_length=256), TranscriptSpeakerIdentity
    ]
    version: Literal[1]
    wordIdentities: Annotated[list[TranscriptWordIdentity], Field(max_length=250000)]


class TranscriptWord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    confidence: Annotated[
        float | None,
        Field(
            description="Alignment score, or null when the provider gave none.",
            ge=0.0,
            le=1.0,
        ),
    ]
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    speaker: str | None
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    text: Annotated[str, Field(min_length=1)]
    timing: WordTiming


class ChapterExport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chapters: list[ChapterRender]
    createdAt: AwareDatetime
    editSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    manifestKey: Annotated[str, Field(max_length=2048, min_length=1)]
    revision: Annotated[int, Field(ge=1, le=9007199254740991)]
    runId: UUID
    version: Literal[1]


class HarnessEvidence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    audioSampleRate: Annotated[int | None, Field(ge=1, le=9007199254740991)]
    boundaries: list[HarnessBoundaryCandidate]
    config: dict[str, Any]
    durationMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    frameRate: PositiveRational | None
    modelVersions: dict[str, str]
    pauses: list[HarnessEvidencePause]
    sentences: list[HarnessEvidenceSentence]
    shots: list[HarnessEvidenceShot]
    sourceFingerprint: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    sourceId: UUID
    sourceStart: SignedRationalTime
    speechCoverage: SpeechCoverage
    transcriptId: UUID
    transcriptRevision: Annotated[int, Field(ge=1, le=9007199254740991)]
    transcriptSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    version: Literal[1]
    videoTimeBase: PositiveRational | None
    words: list[HarnessEvidenceWord]


class TopicAuthorPackagingManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    complete: Literal[True]
    format: Literal["topic-author-packaging-manifest/1"]
    generatorFamilies: list[GeneratorFamily]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inventorySha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    planSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    selection: TopicSelectionDraft
    shardArtifacts: list[HarnessArtifactRef]
    workItemIds: list[WorkItemId]


class TopicAuthorPackagingShard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    draft: TopicSelectionDraft
    format: Literal["topic-author-packaging-shard/1"]
    generatorFamily: Annotated[str, Field(min_length=1)]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inventorySha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    planSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    workItem: TopicAuthorWorkItem


class TopicColdReview(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateId: Annotated[str, Field(max_length=256, min_length=1)]
    coherentTopic: TopicCriterion
    completeDiscussion: TopicCriterion
    intelligibleBeginning: TopicCriterion
    titleFaithful: TopicCriterion


class TopicEditorialPatchInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: Literal["topic_edit"]
    baseEditSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    correctionActiveSeconds: Annotated[float | None, Field(ge=0.0)]
    correctionMeasurementMethod: Annotated[str | None, Field(min_length=1)]
    evidenceSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    mutationKey: UUID
    operations: Annotated[list[TopicEditorialPatchOperation], Field(min_length=1)]
    reason: Annotated[str, Field(min_length=1)]
    runId: UUID
    scope: Scope
    sourceId: UUID
    version: Literal[1]


class TopicOpportunityInventoryManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    complete: Literal[True]
    format: Literal["topic-opportunity-inventory-manifest/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inventory: TopicSelectionDraft
    planSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    sectionIds: Annotated[list[SectionId], Field(min_length=1)]
    shardArtifacts: Annotated[list[HarnessArtifactRef], Field(min_length=1)]


class TopicOpportunityInventoryShard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["topic-opportunity-inventory-shard/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inventory: TopicSelectionDraft
    planSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    section: TopicInventorySection


class TopicPortfolioReview(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidates: list[TopicSourceJudgment]
    findings: list[TopicSelectionFinding]
    missingOpportunities: list[TopicOpportunity]
    opportunities: list[TopicOpportunityJudgment]
    selection: list[TopicSelectionDecision]
    summary: Annotated[str, Field(min_length=1)]


class TopicPortfolioReviewV4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidates: list[TopicSourceJudgment]
    findings: list[TopicSelectionFinding]
    missingOpportunities: list[TopicOpportunity]
    opportunities: list[TopicOpportunityJudgment]
    selection: list[TopicSelectionDecision]
    summary: Annotated[str, Field(min_length=1)]
    handoffs: list[TopicCandidateHandoffJudgment]
    overlaps: list[TopicCandidateOverlapJudgment]


class TopicRepairManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aggregatePatch: TopicSelectionPatchV3
    assessmentSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    authorFamilies: Annotated[list[AuthorFamily], Field(min_length=1)]
    complete: Literal[True]
    format: Literal["topic-repair-manifest/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inspectionArtifacts: Annotated[list[HarnessArtifactRef], Field(min_length=1)]
    planSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    responseArtifacts: Annotated[list[HarnessArtifactRef], Field(min_length=1)]
    selectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    shardArtifacts: Annotated[list[HarnessArtifactRef], Field(min_length=1)]
    workItemIds: Annotated[list[WorkItemId], Field(min_length=1)]


class TopicRepairShard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assessmentSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    authorFamily: Annotated[str, Field(min_length=1)]
    format: Literal["topic-repair-shard/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inspectionArtifact: HarnessArtifactRef
    patch: TopicSelectionPatchV3
    planSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    responseArtifact: HarnessArtifactRef
    selectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    workItem: TopicRepairWorkItem


class TopicSelectionColdReview(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateId: Annotated[str, Field(max_length=256, min_length=1)]
    coherentTopic: TopicCriterion
    completeDiscussion: TopicCriterion
    intelligibleBeginning: TopicCriterion
    titleFaithful: TopicCriterion
    value: TopicValueReview


class TopicSourceReviewManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    complete: Literal[True]
    format: Literal["topic-source-review-manifest/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inspectionArtifacts: list[HarnessArtifactRef]
    planSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    responseArtifacts: Annotated[list[HarnessArtifactRef], Field(min_length=1)]
    review: TopicPortfolioReviewV4
    reviewerFamilies: Annotated[list[ReviewerFamily], Field(min_length=1)]
    selectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    shardArtifacts: Annotated[list[HarnessArtifactRef], Field(min_length=1)]
    workItemIds: Annotated[list[WorkItemId], Field(min_length=1)]


class TopicSourceReviewShard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: Literal["topic-source-review-shard/1"]
    indexSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    inspectionArtifact: HarnessArtifactRef | None
    planSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    responseArtifact: HarnessArtifactRef
    review: TopicPortfolioReviewV4
    reviewerFamily: Annotated[str, Field(min_length=1)]
    selectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    workItem: TopicSourceReviewWorkItem


class TranscriptCorrectionMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: Action
    affectedIdentityIds: Annotated[list[AffectedIdentityId], Field(max_length=500)]
    annotations: TranscriptRevisionAnnotations
    artifactSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    baseRevision: Annotated[int, Field(gt=0, le=9007199254740991)]
    command: (
        Command
        | Command1
        | Command2
        | Command3
        | Command4
        | Command5
        | Command6
        | Command7
        | Command8
    )
    deletedIdentityIds: Annotated[list[DeletedIdentityId], Field(max_length=500)]
    mutationKey: UUID


class TranscriptV1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    durationMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    language: Annotated[
        str,
        Field(
            description="The detected language code, so a wrong guess is visible.",
            min_length=1,
        ),
    ]
    provider: TranscriptProvider
    speakers: Annotated[
        list[str],
        Field(
            description="Every speaker id used by a word, in first-appearance order."
        ),
    ]
    utterances: list[TranscriptUtterance]
    version: Literal[1]
    words: list[TranscriptWord]


class TopicAssessmentCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidateId: Annotated[str, Field(max_length=256, min_length=1)]
    coldReview: TopicColdReview | None
    physicalBoundaryIssues: list[TopicBoundaryIssue]
    reasons: list[str]
    sourceReview: TopicSourceJudgment | None
    status: Status2


class TopicSelectionAssessment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    coldReviews: list[TopicSelectionColdReview]
    evidenceSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    executionStatus: ExecutionStatus
    findings: list[TopicSelectionFinding]
    format: Literal["topic-selection-assessment/2"]
    portfolioReview: TopicPortfolioReviewV4 | None
    proposerFamily: Annotated[str, Field(min_length=1)]
    reasons: list[str]
    responseArtifacts: list[HarnessArtifactRef]
    rubricSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    runId: UUID
    selectionSha256: Annotated[str, Field(pattern="^[a-fA-F0-9]{64}$")]
    verifierFamily: str | None

SEEDED_SCOPE = Scope(
    organizationId=UUID("0192e8a0-0000-7000-8000-000000000001"),
    userId=UUID("0192e8a0-0000-7000-8000-000000000002"),
)
