# Generated from packages/contracts/schemas/contracts.json by scripts/gen_contracts.py.
# Do not edit; change the Zod schema and regenerate (pnpm --filter @temnia/pipeline contracts).
# ruff: noqa
# generated by datamodel-codegen:
#   filename:  contracts.json

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import StrEnum
from uuid import UUID


class Model(RootModel[Any]):
    root: Any


class ArtifactKind(StrEnum):
    master = "master"
    hls = "hls"
    peaks = "peaks"
    thumbnails = "thumbnails"
    audio = "audio"
    shots = "shots"


class ArtifactRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contentType: Annotated[str, Field(min_length=1)]
    kind: ArtifactKind
    metadata: dict[str, Any]
    sizeBytes: Annotated[int, Field(ge=0, le=9007199254740991)]
    storageKey: Annotated[str, Field(min_length=1)]
    storagePrefix: str | None


class HelloOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    greeting: str
    organizationId: Annotated[
        UUID, Field(description="Echoed from the input scope, never invented.")
    ]
    workerHost: str
    workerLanguage: Literal["python"]


class IngestStage(StrEnum):
    probe = "probe"
    hls = "hls"
    publish = "publish"
    thumbnails = "thumbnails"
    audio = "audio"
    peaks = "peaks"
    shots = "shots"
    finalize = "finalize"


class ProbeResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    audioChannels: Annotated[int | None, Field(ge=0, le=9007199254740991)]
    audioCodec: str | None
    durationMs: Annotated[int, Field(gt=0, le=9007199254740991)]
    fps: Annotated[float | None, Field(gt=0.0)]
    height: Annotated[int | None, Field(gt=0, le=9007199254740991)]
    sizeBytes: Annotated[int, Field(ge=0, le=9007199254740991)]
    variableFrameRate: bool
    videoCodec: str | None
    width: Annotated[int | None, Field(gt=0, le=9007199254740991)]


class Scope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organizationId: Annotated[
        UUID, Field(description="The organization every row is scoped to.")
    ]
    userId: Annotated[
        UUID, Field(description="The acting user inside that organization.")
    ]


class TranscribeInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifactPrefix: Annotated[
        str,
        Field(
            description="The source prefix; the transcript is written under it.",
            min_length=1,
        ),
    ]
    audioKey: Annotated[
        str,
        Field(
            description="The audio extract the provider reads; never the master.",
            min_length=1,
        ),
    ]
    durationMs: Annotated[
        int,
        Field(
            description="The probed duration; what the engine is metered against.",
            gt=0,
            le=9007199254740991,
        ),
    ]
    scope: Scope
    sourceId: UUID


class TranscriptProvider(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: Annotated[str, Field(min_length=1)]
    name: Annotated[str, Field(min_length=1)]
    version: Annotated[str, Field(min_length=1)]


class TranscriptStage(StrEnum):
    download = "download"
    model = "model"
    transcribe = "transcribe"
    align = "align"
    diarize = "diarize"
    write = "write"
    retrying = "retrying"


class TranscriptUtterance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    speaker: str | None
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class WordTiming(StrEnum):
    aligned = "aligned"
    interpolated = "interpolated"


class HelloInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str, Field(description="Who to greet.", max_length=80, min_length=1)
    ]
    scope: Scope


class IngestInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifactPrefix: Annotated[
        str,
        Field(
            description="Prefix every derived artifact is written under; ends with '/'.",
            min_length=1,
        ),
    ]
    masterKey: Annotated[
        str, Field(description="The uploaded master's storage key.", min_length=1)
    ]
    scope: Scope
    sourceId: UUID


class IngestOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifacts: list[ArtifactRecord]
    organizationId: Annotated[
        UUID, Field(description="Echoed from the input scope, never invented.")
    ]
    probe: ProbeResult
    processingSeconds: Annotated[
        int,
        Field(
            description="Wall-clock seconds the worker spent.",
            ge=0,
            le=9007199254740991,
        ),
    ]
    sourceId: UUID
    storageBytes: Annotated[
        int,
        Field(
            description="Sum of the artifact rows written.", ge=0, le=9007199254740991
        ),
    ]


class TranscribeOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    durationMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    language: Annotated[str, Field(min_length=1)]
    organizationId: Annotated[
        UUID, Field(description="Echoed from the input scope, never invented.")
    ]
    provider: TranscriptProvider
    revision: Annotated[int, Field(gt=0, le=9007199254740991)]
    sourceId: UUID
    speakerCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    storageKey: Annotated[str, Field(min_length=1)]
    wordCount: Annotated[int, Field(ge=0, le=9007199254740991)]


class TranscriptWord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    confidence: Annotated[
        float | None,
        Field(
            description="Alignment score, or null when the provider gave none.",
            ge=0.0,
            le=1.0,
        ),
    ]
    endMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    speaker: str | None
    startMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    text: Annotated[str, Field(min_length=1)]
    timing: WordTiming


class TranscriptV1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    durationMs: Annotated[int, Field(ge=0, le=9007199254740991)]
    language: Annotated[
        str,
        Field(
            description="The detected language code, so a wrong guess is visible.",
            min_length=1,
        ),
    ]
    provider: TranscriptProvider
    speakers: Annotated[
        list[str],
        Field(
            description="Every speaker id used by a word, in first-appearance order."
        ),
    ]
    utterances: list[TranscriptUtterance]
    version: Literal[1]
    words: list[TranscriptWord]
